namespace XMLSharpCompiler;

public static class TokenFollowers
{
    public static readonly Dictionary<Type, HashSet<Type>> ValidFollowers = new()
    {
        // values
        [typeof(NumberToken)] = [
           typeof(SemicolonToken),
            typeof(AddToken),
            typeof(SubtractToken),
            typeof(MultiplyToken),
            typeof(DivideToken),
            typeof(ModuloToken),
            typeof(EqualsToken),
            typeof(NotEqualsToken),
            typeof(GreaterToken),
            typeof(LessToken),
            typeof(GreaterOrEqualsToken),
            typeof(LessOrEqualsToken),
        ],
        [typeof(TextToken)] = [
           typeof(SemicolonToken),
            typeof(ConcatToken),
            typeof(EqualsToken),
            typeof(NotEqualsToken),
        ],
        [typeof(IdentifierToken)] = [
           typeof(SemicolonToken),
            typeof(AssignmentToken),
            typeof(AddToken),
            typeof(SubtractToken),
            typeof(MultiplyToken),
            typeof(DivideToken),
            typeof(ModuloToken),
            typeof(EqualsToken),
            typeof(NotEqualsToken),
            typeof(GreaterToken),
            typeof(LessToken),
            typeof(GreaterOrEqualsToken),
            typeof(LessOrEqualsToken),
            typeof(AndToken),
            typeof(OrToken),
            typeof(XorToken),
            typeof(ConcatToken),
        ],
        [typeof(YesToken)] = [
           typeof(SemicolonToken),
            typeof(AndToken),
            typeof(OrToken),
            typeof(XorToken),
            typeof(EqualsToken),
            typeof(NotEqualsToken),
        ],
        [typeof(NoToken)] = [
           typeof(SemicolonToken),
            typeof(AndToken),
            typeof(OrToken),
            typeof(XorToken),
            typeof(EqualsToken),
            typeof(NotEqualsToken),
        ],
        // operators - must be followed by a value
        [typeof(AddToken)] = [
           typeof(NumberToken),
            typeof(IdentifierToken),
            typeof(OpenParenToken),
        ],
        [typeof(SubtractToken)] = [
           typeof(NumberToken),
            typeof(IdentifierToken),
            typeof(OpenParenToken),
        ],
        [typeof(MultiplyToken)] = [
           typeof(NumberToken),
            typeof(IdentifierToken),
            typeof(OpenParenToken),
        ],
        [typeof(DivideToken)] = [
           typeof(NumberToken),
            typeof(IdentifierToken),
            typeof(OpenParenToken),
        ],
        [typeof(ModuloToken)] = [
           typeof(NumberToken),
            typeof(IdentifierToken),
            typeof(OpenParenToken),
        ],
        [typeof(ConcatToken)] = [
           typeof(TextToken),
            typeof(IdentifierToken),
            typeof(OpenParenToken),
        ],
        [typeof(AssignmentToken)] = [
           typeof(NumberToken),
            typeof(TextToken),
            typeof(YesToken),
            typeof(NoToken),
            typeof(IdentifierToken),
            typeof(OpenParenToken),
            typeof(NotToken),
        ],
        [typeof(EqualsToken)] = [
           typeof(NumberToken),
            typeof(TextToken),
            typeof(YesToken),
            typeof(NoToken),
            typeof(IdentifierToken),
            typeof(OpenParenToken),
            typeof(NotToken),
        ],
        [typeof(NotEqualsToken)] = [
           typeof(NumberToken),
            typeof(TextToken),
            typeof(YesToken),
            typeof(NoToken),
            typeof(IdentifierToken),
            typeof(OpenParenToken),
            typeof(NotToken),
        ],
        [typeof(GreaterToken)] = [
           typeof(NumberToken),
            typeof(IdentifierToken),
            typeof(OpenParenToken),
        ],
        [typeof(LessToken)] = [
           typeof(NumberToken),
            typeof(IdentifierToken),
            typeof(OpenParenToken),
        ],
        [typeof(GreaterOrEqualsToken)] = [
           typeof(NumberToken),
            typeof(IdentifierToken),
            typeof(OpenParenToken),
        ],
        [typeof(LessOrEqualsToken)] = [
           typeof(NumberToken),
            typeof(IdentifierToken),
            typeof(OpenParenToken),
        ],
        [typeof(AndToken)] = [
           typeof(YesToken),
            typeof(NoToken),
            typeof(IdentifierToken),
            typeof(OpenParenToken),
            typeof(NotToken),
        ],
        [typeof(OrToken)] = [
           typeof(YesToken),
            typeof(NoToken),
            typeof(IdentifierToken),
            typeof(OpenParenToken),
            typeof(NotToken),
        ],
        [typeof(XorToken)] = [
           typeof(YesToken),
            typeof(NoToken),
            typeof(IdentifierToken),
            typeof(OpenParenToken),
            typeof(NotToken),
        ],
        [typeof(NotToken)] = [
           typeof(YesToken),
            typeof(NoToken),
            typeof(IdentifierToken),
            typeof(OpenParenToken),
        ],
        // parens
        [typeof(OpenParenToken)] = [
           typeof(NumberToken),
            typeof(TextToken),
            typeof(YesToken),
            typeof(NoToken),
            typeof(IdentifierToken),
            typeof(NotToken),
            typeof(OpenParenToken),
        ],
        [typeof(CloseParenToken)] = [
           typeof(SemicolonToken),
            typeof(AddToken),
            typeof(SubtractToken),
            typeof(MultiplyToken),
            typeof(DivideToken),
            typeof(ModuloToken),
            typeof(EqualsToken),
            typeof(NotEqualsToken),
            typeof(GreaterToken),
            typeof(LessToken),
            typeof(GreaterOrEqualsToken),
            typeof(LessOrEqualsToken),
            typeof(AndToken),
            typeof(OrToken),
            typeof(XorToken),
            typeof(CloseParenToken),
        ],
        // print
        [typeof(PrintToken)] = [
           typeof(NumberToken),
            typeof(TextToken),
            typeof(YesToken),
            typeof(NoToken),
            typeof(IdentifierToken),
            typeof(OpenParenToken),
            typeof(NotToken),
        ],
        // variable definition - already handled by VariableDeclarationRule
        [typeof(VariableDefinitionToken)] = [
           typeof(IdentifierToken),
        ],
    };
}